import { createFileRoute } from '@tanstack/react-router'
import { eq } from 'drizzle-orm'
import { db, apps } from '../db'

export const Route = createFileRoute('/api/manifest/$appId')({
  server: {
    handlers: {
      GET: async ({ params }) => {
        const { appId } = params

        const app = await db.query.apps.findFirst({
          where: eq(apps.id, appId),
        })

        if (!app) {
          return new Response(JSON.stringify({ error: 'App not found' }), {
            status: 404,
            headers: { 'Content-Type': 'application/json' },
          })
        }

        // Generate a dynamic manifest
        const manifest = {
          name: app.name || 'Emagine App',
          short_name: app.name?.substring(0, 12) || 'App',
          description: app.description || app.prompt || 'Generated by Emagine',
          start_url: `/a/${appId}`,
          display: 'standalone',
          background_color: '#0f172a',
          theme_color: '#6366f1',
          icons: [
            {
              // We could generate an actual image from the emoji icon, 
              // but for now we'll use a generic icon or the favicon
              src: '/favicon.svg',
              sizes: 'any',
              type: 'image/svg+xml'
            },
            {
              src: '/pwa-192x192.png',
              sizes: '192x192',
              type: 'image/png'
            },
            {
              src: '/pwa-512x512.png',
              sizes: '512x512',
              type: 'image/png'
            }
          ]
        }

        return new Response(JSON.stringify(manifest), {
          headers: {
            'Content-Type': 'application/manifest+json',
            'Cache-Control': 'public, max-age=3600'
          },
        })
      }
    }
  }
})
