/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSettingsRouteImport } from './routes/api.settings'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiGenerateRouteImport } from './routes/api.generate'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as ApiAppsRouteImport } from './routes/api.apps'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAppsAppIdRouteImport } from './routes/api.apps.$appId'
import { Route as ApiAppsAppIdStreamRouteImport } from './routes/api.apps.$appId.stream'
import { Route as ApiAppsAppIdServeRouteImport } from './routes/api.apps.$appId.serve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsRoute = ApiAppsRouteImport.update({
  id: '/api/apps',
  path: '/api/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsAppIdRoute = ApiAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => ApiAppsRoute,
} as any)
const ApiAppsAppIdStreamRoute = ApiAppsAppIdStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiAppsAppIdRoute,
} as any)
const ApiAppsAppIdServeRoute = ApiAppsAppIdServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => ApiAppsAppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/apps': typeof ApiAppsRouteWithChildren
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/apps/$appId': typeof ApiAppsAppIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/apps/$appId/serve': typeof ApiAppsAppIdServeRoute
  '/api/apps/$appId/stream': typeof ApiAppsAppIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/apps': typeof ApiAppsRouteWithChildren
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/apps/$appId': typeof ApiAppsAppIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/apps/$appId/serve': typeof ApiAppsAppIdServeRoute
  '/api/apps/$appId/stream': typeof ApiAppsAppIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/apps': typeof ApiAppsRouteWithChildren
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/apps/$appId': typeof ApiAppsAppIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/apps/$appId/serve': typeof ApiAppsAppIdServeRoute
  '/api/apps/$appId/stream': typeof ApiAppsAppIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/apps'
    | '/api/demo-names'
    | '/api/generate'
    | '/api/health'
    | '/api/settings'
    | '/api/apps/$appId'
    | '/api/auth/$'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/apps/$appId/serve'
    | '/api/apps/$appId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/apps'
    | '/api/demo-names'
    | '/api/generate'
    | '/api/health'
    | '/api/settings'
    | '/api/apps/$appId'
    | '/api/auth/$'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/apps/$appId/serve'
    | '/api/apps/$appId/stream'
  id:
    | '__root__'
    | '/'
    | '/api/apps'
    | '/api/demo-names'
    | '/api/generate'
    | '/api/health'
    | '/api/settings'
    | '/api/apps/$appId'
    | '/api/auth/$'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/apps/$appId/serve'
    | '/api/apps/$appId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAppsRoute: typeof ApiAppsRouteWithChildren
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps': {
      id: '/api/apps'
      path: '/api/apps'
      fullPath: '/api/apps'
      preLoaderRoute: typeof ApiAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$appId': {
      id: '/api/apps/$appId'
      path: '/$appId'
      fullPath: '/api/apps/$appId'
      preLoaderRoute: typeof ApiAppsAppIdRouteImport
      parentRoute: typeof ApiAppsRoute
    }
    '/api/apps/$appId/stream': {
      id: '/api/apps/$appId/stream'
      path: '/stream'
      fullPath: '/api/apps/$appId/stream'
      preLoaderRoute: typeof ApiAppsAppIdStreamRouteImport
      parentRoute: typeof ApiAppsAppIdRoute
    }
    '/api/apps/$appId/serve': {
      id: '/api/apps/$appId/serve'
      path: '/serve'
      fullPath: '/api/apps/$appId/serve'
      preLoaderRoute: typeof ApiAppsAppIdServeRouteImport
      parentRoute: typeof ApiAppsAppIdRoute
    }
  }
}

interface ApiAppsAppIdRouteChildren {
  ApiAppsAppIdServeRoute: typeof ApiAppsAppIdServeRoute
  ApiAppsAppIdStreamRoute: typeof ApiAppsAppIdStreamRoute
}

const ApiAppsAppIdRouteChildren: ApiAppsAppIdRouteChildren = {
  ApiAppsAppIdServeRoute: ApiAppsAppIdServeRoute,
  ApiAppsAppIdStreamRoute: ApiAppsAppIdStreamRoute,
}

const ApiAppsAppIdRouteWithChildren = ApiAppsAppIdRoute._addFileChildren(
  ApiAppsAppIdRouteChildren,
)

interface ApiAppsRouteChildren {
  ApiAppsAppIdRoute: typeof ApiAppsAppIdRouteWithChildren
}

const ApiAppsRouteChildren: ApiAppsRouteChildren = {
  ApiAppsAppIdRoute: ApiAppsAppIdRouteWithChildren,
}

const ApiAppsRouteWithChildren =
  ApiAppsRoute._addFileChildren(ApiAppsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAppsRoute: ApiAppsRouteWithChildren,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
